FROM debian:jessie

# persistent / runtime deps
RUN apt-get update && apt-get install -y ca-certificates curl libpcre3 librecode0 libsqlite3-0 libxml2 --no-install-recommends && rm -r /var/lib/apt/lists/*

# phpize deps
RUN apt-get update && apt-get install -y autoconf file gcc libc-dev make pkg-config re2c --no-install-recommends && rm -r /var/lib/apt/lists/*

ENV PHP_INI_DIR /usr/local/etc/php
RUN mkdir -p $PHP_INI_DIR/conf.d

##<autogenerated>##
ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
##</autogenerated>##

ENV PHP_VERSION 7.0.0

RUN buildDeps=" \
		$PHP_EXTRA_BUILD_DEPS \
		bzip2 \
		libcurl4-openssl-dev \
		libpcre3-dev \
		libreadline6-dev \
		librecode-dev \
		libsqlite3-dev \
		libssl-dev \
		libxml2-dev \
	" \
	&& set -x \
	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \

	&& mkdir ~/tmp \
	&& cd ~/tmp \
	&& git clone git@git.php.net:php-src.git \
	&& cd php-src \
	&& ./buildconf \
	&& ./configure \
		--with-config-file-path="$PHP_INI_DIR" \
		--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
	    --prefix=$HOME/tmp/usr \
	    --with-config-file-path=$HOME/tmp/usr/etc \
	    --enable-mbstring \
	    --enable-zip \
	    --enable-bcmath \
	    --enable-pcntl \
	    --enable-ftp \
	    --enable-exif \
	    --enable-calendar \
	    --enable-sysvmsg \
	    --enable-sysvsem \
	    --enable-sysvshm \
	    --enable-wddx \
	    --with-curl \
	    --with-mcrypt \
	    --with-iconv \
	    --with-gmp \
	    --with-pspell \
	    --with-gd \
	    --with-jpeg-dir=/usr \
	    --with-png-dir=/usr \
	    --with-zlib-dir=/usr \
	    --with-xpm-dir=/usr \
	    --with-freetype-dir=/usr \
	    --with-t1lib=/usr \
	    --enable-gd-native-ttf \
	    --enable-gd-jis-conv \
	    --with-openssl \
	    --with-mysql=/usr \
	    --with-pdo-mysql=/usr \
	    --with-gettext=/usr \
	    --with-zlib=/usr \
	    --with-bz2=/usr \
	    --with-recode=/usr \
	    --with-mysqli=/usr/bin/mysql_config
	&& make -j"$(nproc)" \
	&& make install \
	&& { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps \
	&& make clean

COPY docker-php-ext-* /usr/local/bin/

##<autogenerated>##
WORKDIR /var/www/html
COPY php-fpm.conf /usr/local/etc/

EXPOSE 9000
CMD ["php-fpm"]
##</autogenerated>##